apiVersion: 1

datasources:
  - name: InfluxDB-k6
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086
    isDefault: false
    editable: true
    uid: DS_INFLUXDB-K6
  - name: InfluxDB-Newman
    type: influxdb
    access: proxy
    database: newman
    url: http://influxdb:8086
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      httpMode: POST
      timeInterval: "5s"
    isDefault: true
    editable: true
    uid: DS_INFLUXDB-NEWMAN
