apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-kafka
spec:
  type: pubsub.kafka
  metadata:
      # Kafka broker connection setting
    - name: brokers
      # Comma separated list of kafka brokers
      value: "localhost:19092"
      # Enable auth. Default is "false"
    - name: authRequired
      value: "false"