services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    ports:
      - 5080:5080
    volumes:
      - $PWD/data:/data
    environment:
      - ZO_ROOT_USER_EMAIL=root@root.com
      - ZO_ROOT_USER_PASSWORD=root

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
