services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=newman
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - performance-network

  newman:
    build:
      context: ./postman
      dockerfile: Dockerfile
    container_name: newman-reporter
    volumes:
      - ./postman/collections:/collections
      - ./postman/environments:/environments
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DATABASE=newman
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=admin
    depends_on:
      - influxdb
    networks:
      - performance-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    networks:
      - performance-network
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    volumes:
      - ./k6:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
     # - K6_SCRIPT=${K6_SCRIPT:-test.js}
    networks:
      - performance-network
    depends_on:
      - influxdb
    # command: run /scripts/${K6_SCRIPT:-test.js}

networks:
  performance-network:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data:
